variables:
  CABAL_DIR: "$CI_PROJECT_DIR/.cabal-dir"
  CABAL_CONFIG: "$CI_PROJECT_DIR/.cabal-dir/config"

default:
  image: haskell:9.4
  cache:
    key:
      files:
        - lemmatchers.cabal
    paths:
      - dist-newstyle
      - $CABAL_DIR

stages:
  - build
  - deploy_api_docs

build_test_doc:
  stage: build
  script:
    - if [ -f "$CABAL_CONFIG" ]; then cabal user-config update; else cabal user-config init; fi
    - cabal update
    - cabal build --only-dependencies --enable-tests
    - cabal build --enable-tests
    - cabal test --test-show-details=direct
    - cabal haddock --builddir=haddock_build --haddock-hyperlinked-source --haddock-html-location='https://hackage.haskell.org/package/$pkg-$version/docs'
    - mv $(find haddock_build -wholename '*doc/html/lemmatchers' | head -n 1) apidocs/
  artifacts:
    paths:
      - apidocs

pages:
  stage: deploy_api_docs
  only:
    - main
  dependencies:
    - build_test_doc
  script:
    - mkdir -p public
    - cp -r apidocs public/
  artifacts:
    paths:
      - public
